parser: babel-eslint
parserOptions:
  ecmaVersion: 6
extends:
  - airbnb-base
  - plugin:flowtype/recommended
  - plugin:prettier/recommended
plugins:
  - flowtype
  - prettier
rules:
  class-methods-use-this: off
  no-param-reassign: off
  no-underscore-dangle: off
  no-unused-vars: warn
  no-warning-comments: warn
  require-jsdoc:
    - error
    -
      require:
        FunctionDeclaration: true
        MethodDefinition: true
        ClassDeclaration: true
  valid-jsdoc: error
  no-unused-expressions: off
  flowtype/no-unused-expressions: error
  prettier/prettier:
    - error
    - trailingComma: es5
      singleQuote: true
  flowtype/generic-spacing: off
